
from PyQt5 import QtCore, QtGui, QtWidgets
from MongoDb.busquedasId import*
class Ui_MenuCallCenter(object):
        def setupUi(self, MenuCallCenter):
                MenuCallCenter.setObjectName("MenuCallCenter")
                MenuCallCenter.resize(800, 600)
                self.centralwidget = QtWidgets.QWidget(MenuCallCenter)
                self.centralwidget.setObjectName("centralwidget")
                self.MenueEliminarUsuario = QtWidgets.QTabWidget(self.centralwidget)
                self.MenueEliminarUsuario.setGeometry(QtCore.QRect(10, 10, 781, 571))
                self.MenueEliminarUsuario.setTabBarAutoHide(False)
                self.MenueEliminarUsuario.setObjectName("MenueEliminarUsuario")
                self.MenuBuscar = QtWidgets.QWidget()
                self.MenuBuscar.setEnabled(True)
                self.MenuBuscar.setObjectName("MenuBuscar")
                self.BotonBuscar = QtWidgets.QPushButton(self.MenuBuscar)
                self.BotonBuscar.setGeometry(QtCore.QRect(270, 490, 231, 31))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.BotonBuscar.setFont(font)
                self.BotonBuscar.setStyleSheet("QPushButton{\n"
        "    color:#fff;\n"
        "    border-radius:10px;\n"
        "    background:#EC3333\n"
        "    \n"
        "}\n"
        "QPushButthon{\n"
        "    color:black;\n"
        "    background:#D90808\n"
        "}")
                self.BotonBuscar.setObjectName("BotonBuscar")
                self.NombreAdmin = QtWidgets.QLabel(self.MenuBuscar)
                self.NombreAdmin.setGeometry(QtCore.QRect(60, 30, 151, 31))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.NombreAdmin.setFont(font)
                self.NombreAdmin.setObjectName("NombreAdmin")
                self.IdAdministrador = QtWidgets.QLabel(self.MenuBuscar)
                self.IdAdministrador.setGeometry(QtCore.QRect(410, 30, 121, 31))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.IdAdministrador.setFont(font)
                self.IdAdministrador.setObjectName("IdAdministrador")
                self.label_18 = QtWidgets.QLabel(self.MenuBuscar)
                self.label_18.setGeometry(QtCore.QRect(420, 220, 81, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_18.setFont(font)
                self.label_18.setObjectName("label_18")
                self.cajaCaso_2 = QtWidgets.QLineEdit(self.MenuBuscar)
                self.cajaCaso_2.setEnabled(False)
                self.cajaCaso_2.setGeometry(QtCore.QRect(420, 240, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaCaso_2.setFont(font)
                self.cajaCaso_2.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaCaso_2.setObjectName("cajaCaso_2")
                self.label_19 = QtWidgets.QLabel(self.MenuBuscar)
                self.label_19.setGeometry(QtCore.QRect(60, 320, 161, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_19.setFont(font)
                self.label_19.setObjectName("label_19")
                self.label_20 = QtWidgets.QLabel(self.MenuBuscar)
                self.label_20.setGeometry(QtCore.QRect(60, 270, 91, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_20.setFont(font)
                self.label_20.setObjectName("label_20")
                self.label_21 = QtWidgets.QLabel(self.MenuBuscar)
                self.label_21.setGeometry(QtCore.QRect(420, 170, 121, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_21.setFont(font)
                self.label_21.setObjectName("label_21")
                self.cajaNombre_2 = QtWidgets.QLineEdit(self.MenuBuscar)
                self.cajaNombre_2.setEnabled(False)
                self.cajaNombre_2.setGeometry(QtCore.QRect(60, 240, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaNombre_2.setFont(font)
                self.cajaNombre_2.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaNombre_2.setObjectName("cajaNombre_2")
                self.cajaTelefono_2 = QtWidgets.QLineEdit(self.MenuBuscar)
                self.cajaTelefono_2.setEnabled(False)
                self.cajaTelefono_2.setGeometry(QtCore.QRect(60, 290, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaTelefono_2.setFont(font)
                self.cajaTelefono_2.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaTelefono_2.setObjectName("cajaTelefono_2")
                self.cajaObservaciones_2 = QtWidgets.QLineEdit(self.MenuBuscar)
                self.cajaObservaciones_2.setEnabled(False)
                self.cajaObservaciones_2.setGeometry(QtCore.QRect(420, 290, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaObservaciones_2.setFont(font)
                self.cajaObservaciones_2.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaObservaciones_2.setObjectName("cajaObservaciones_2")
                self.cajaICiudad_2 = QtWidgets.QLineEdit(self.MenuBuscar)
                self.cajaICiudad_2.setEnabled(False)
                self.cajaICiudad_2.setGeometry(QtCore.QRect(60, 340, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaICiudad_2.setFont(font)
                self.cajaICiudad_2.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaICiudad_2.setObjectName("cajaICiudad_2")
                self.label_22 = QtWidgets.QLabel(self.MenuBuscar)
                self.label_22.setGeometry(QtCore.QRect(420, 270, 121, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_22.setFont(font)
                self.label_22.setObjectName("label_22")
                self.cajaId_3 = QtWidgets.QLineEdit(self.MenuBuscar)
                self.cajaId_3.setGeometry(QtCore.QRect(60, 140, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaId_3.setFont(font)
                self.cajaId_3.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaId_3.setObjectName("cajaId_3")
                self.cajaAvenida_2 = QtWidgets.QLineEdit(self.MenuBuscar)
                self.cajaAvenida_2.setEnabled(False)
                self.cajaAvenida_2.setGeometry(QtCore.QRect(60, 400, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaAvenida_2.setFont(font)
                self.cajaAvenida_2.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaAvenida_2.setObjectName("cajaAvenida_2")
                self.cajaApellido_2 = QtWidgets.QLineEdit(self.MenuBuscar)
                self.cajaApellido_2.setEnabled(False)
                self.cajaApellido_2.setGeometry(QtCore.QRect(60, 190, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaApellido_2.setFont(font)
                self.cajaApellido_2.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaApellido_2.setObjectName("cajaApellido_2")
                self.label_23 = QtWidgets.QLabel(self.MenuBuscar)
                self.label_23.setGeometry(QtCore.QRect(60, 120, 91, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_23.setFont(font)
                self.label_23.setObjectName("label_23")
                self.label_24 = QtWidgets.QLabel(self.MenuBuscar)
                self.label_24.setGeometry(QtCore.QRect(60, 170, 91, 21))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_24.setFont(font)
                self.label_24.setObjectName("label_24")
                self.cajaCallePrincipal_2 = QtWidgets.QLineEdit(self.MenuBuscar)
                self.cajaCallePrincipal_2.setEnabled(False)
                self.cajaCallePrincipal_2.setGeometry(QtCore.QRect(420, 140, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaCallePrincipal_2.setFont(font)
                self.cajaCallePrincipal_2.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaCallePrincipal_2.setObjectName("cajaCallePrincipal_2")
                self.label_25 = QtWidgets.QLabel(self.MenuBuscar)
                self.label_25.setGeometry(QtCore.QRect(420, 120, 121, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_25.setFont(font)
                self.label_25.setObjectName("label_25")
                self.label_26 = QtWidgets.QLabel(self.MenuBuscar)
                self.label_26.setGeometry(QtCore.QRect(60, 380, 171, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_26.setFont(font)
                self.label_26.setObjectName("label_26")
                self.label_27 = QtWidgets.QLabel(self.MenuBuscar)
                self.label_27.setGeometry(QtCore.QRect(60, 220, 91, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_27.setFont(font)
                self.label_27.setObjectName("label_27")
                self.cajaCalleSecundaria_2 = QtWidgets.QLineEdit(self.MenuBuscar)
                self.cajaCalleSecundaria_2.setEnabled(False)
                self.cajaCalleSecundaria_2.setGeometry(QtCore.QRect(420, 190, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaCalleSecundaria_2.setFont(font)
                self.cajaCalleSecundaria_2.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaCalleSecundaria_2.setObjectName("cajaCalleSecundaria_2")
                self.BotonBuscar_2 = QtWidgets.QPushButton(self.MenuBuscar)
                self.BotonBuscar_2.setGeometry(QtCore.QRect(270, 450, 231, 31))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.BotonBuscar_2.setFont(font)
                self.BotonBuscar_2.setStyleSheet("QPushButton{\n"
        "    color:#fff;\n"
        "    border-radius:10px;\n"
        "    background:#EC3333\n"
        "    \n"
        "}\n"
        "QPushButthon{\n"
        "    color:black;\n"
        "    background:#D90808\n"
        "}")
                self.BotonBuscar_2.setObjectName("BotonBuscar_2")
                self.CajaNombrAdmin = QtWidgets.QLineEdit(self.MenuBuscar)
                self.CajaNombrAdmin.setEnabled(False)
                self.CajaNombrAdmin.setGeometry(QtCore.QRect(210, 30, 161, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.CajaNombrAdmin.setFont(font)
                self.CajaNombrAdmin.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.CajaNombrAdmin.setObjectName("CajaNombrAdmin")
                self.CajaIdAdmin = QtWidgets.QLineEdit(self.MenuBuscar)
                self.CajaIdAdmin.setEnabled(False)
                self.CajaIdAdmin.setGeometry(QtCore.QRect(540, 30, 191, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.CajaIdAdmin.setFont(font)
                self.CajaIdAdmin.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.CajaIdAdmin.setObjectName("CajaIdAdmin")
                self.MenueEliminarUsuario.addTab(self.MenuBuscar, "")
                self.MenuAniadir = QtWidgets.QWidget()
                self.MenuAniadir.setObjectName("MenuAniadir")
                self.BotonSituacion = QtWidgets.QPushButton(self.MenuAniadir)
                self.BotonSituacion.setGeometry(QtCore.QRect(270, 500, 231, 31))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.BotonSituacion.setFont(font)
                self.BotonSituacion.setStyleSheet("QPushButton{\n"
        "    color:#fff;\n"
        "    border-radius:10px;\n"
        "    background:#EC3333\n"
        "    \n"
        "}\n"
        "QPushButthon{\n"
        "    color:black;\n"
        "    background:#D90808\n"
        "}")
                self.BotonSituacion.setObjectName("BotonSituacion")
                self.label = QtWidgets.QLabel(self.MenuAniadir)
                self.label.setGeometry(QtCore.QRect(80, 90, 91, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label.setFont(font)
                self.label.setObjectName("label")
                self.label_2 = QtWidgets.QLabel(self.MenuAniadir)
                self.label_2.setGeometry(QtCore.QRect(80, 140, 91, 21))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_2.setFont(font)
                self.label_2.setObjectName("label_2")
                self.label_3 = QtWidgets.QLabel(self.MenuAniadir)
                self.label_3.setGeometry(QtCore.QRect(80, 190, 91, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_3.setFont(font)
                self.label_3.setObjectName("label_3")
                self.label_4 = QtWidgets.QLabel(self.MenuAniadir)
                self.label_4.setGeometry(QtCore.QRect(80, 240, 91, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_4.setFont(font)
                self.label_4.setObjectName("label_4")
                self.label_5 = QtWidgets.QLabel(self.MenuAniadir)
                self.label_5.setGeometry(QtCore.QRect(80, 290, 161, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_5.setFont(font)
                self.label_5.setObjectName("label_5")
                self.label_6 = QtWidgets.QLabel(self.MenuAniadir)
                self.label_6.setGeometry(QtCore.QRect(80, 350, 171, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_6.setFont(font)
                self.label_6.setObjectName("label_6")
                self.cajaId = QtWidgets.QLineEdit(self.MenuAniadir)
                self.cajaId.setGeometry(QtCore.QRect(80, 110, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaId.setFont(font)
                self.cajaId.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaId.setObjectName("cajaId")
                self.BotonSituacion_2 = QtWidgets.QPushButton(self.MenuAniadir)
                self.BotonSituacion_2.setGeometry(QtCore.QRect(270, 460, 231, 31))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.BotonSituacion_2.setFont(font)
                self.BotonSituacion_2.setStyleSheet("QPushButton{\n"
        "    color:#fff;\n"
        "    border-radius:10px;\n"
        "    background:#EC3333\n"
        "    \n"
        "}\n"
        "QPushButthon{\n"
        "    color:black;\n"
        "    background:#D90808\n"
        "}")
                self.BotonSituacion_2.setObjectName("BotonSituacion_2")
                self.cajaApellido = QtWidgets.QLineEdit(self.MenuAniadir)
                self.cajaApellido.setEnabled(False)
                self.cajaApellido.setGeometry(QtCore.QRect(80, 160, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaApellido.setFont(font)
                self.cajaApellido.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaApellido.setObjectName("cajaApellido")
                self.cajaNombre = QtWidgets.QLineEdit(self.MenuAniadir)
                self.cajaNombre.setEnabled(False)
                self.cajaNombre.setGeometry(QtCore.QRect(80, 210, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaNombre.setFont(font)
                self.cajaNombre.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaNombre.setObjectName("cajaNombre")
                self.cajaTelefono = QtWidgets.QLineEdit(self.MenuAniadir)
                self.cajaTelefono.setEnabled(True)
                self.cajaTelefono.setGeometry(QtCore.QRect(80, 260, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaTelefono.setFont(font)
                self.cajaTelefono.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaTelefono.setObjectName("cajaTelefono")
                self.cajaICiudad = QtWidgets.QLineEdit(self.MenuAniadir)
                self.cajaICiudad.setEnabled(True)
                self.cajaICiudad.setGeometry(QtCore.QRect(80, 310, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaICiudad.setFont(font)
                self.cajaICiudad.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaICiudad.setObjectName("cajaICiudad")
                self.cajaAvenida = QtWidgets.QLineEdit(self.MenuAniadir)
                self.cajaAvenida.setGeometry(QtCore.QRect(80, 370, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaAvenida.setFont(font)
                self.cajaAvenida.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaAvenida.setObjectName("cajaAvenida")
                self.label_13 = QtWidgets.QLabel(self.MenuAniadir)
                self.label_13.setGeometry(QtCore.QRect(290, 20, 191, 31))
                font = QtGui.QFont()
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.label_13.setFont(font)
                self.label_13.setObjectName("label_13")
                self.cajaCallePrincipal = QtWidgets.QLineEdit(self.MenuAniadir)
                self.cajaCallePrincipal.setGeometry(QtCore.QRect(440, 100, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaCallePrincipal.setFont(font)
                self.cajaCallePrincipal.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaCallePrincipal.setObjectName("cajaCallePrincipal")
                self.label_14 = QtWidgets.QLabel(self.MenuAniadir)
                self.label_14.setGeometry(QtCore.QRect(440, 80, 121, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_14.setFont(font)
                self.label_14.setObjectName("label_14")
                self.cajaCalleSecundaria = QtWidgets.QLineEdit(self.MenuAniadir)
                self.cajaCalleSecundaria.setGeometry(QtCore.QRect(440, 150, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaCalleSecundaria.setFont(font)
                self.cajaCalleSecundaria.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaCalleSecundaria.setObjectName("cajaCalleSecundaria")
                self.label_15 = QtWidgets.QLabel(self.MenuAniadir)
                self.label_15.setGeometry(QtCore.QRect(440, 130, 121, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_15.setFont(font)
                self.label_15.setObjectName("label_15")
                self.cajaCaso = QtWidgets.QLineEdit(self.MenuAniadir)
                self.cajaCaso.setGeometry(QtCore.QRect(440, 200, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaCaso.setFont(font)
                self.cajaCaso.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaCaso.setObjectName("cajaCaso")
                self.label_16 = QtWidgets.QLabel(self.MenuAniadir)
                self.label_16.setGeometry(QtCore.QRect(440, 180, 81, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_16.setFont(font)
                self.label_16.setObjectName("label_16")
                self.label_17 = QtWidgets.QLabel(self.MenuAniadir)
                self.label_17.setGeometry(QtCore.QRect(440, 230, 121, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_17.setFont(font)
                self.label_17.setObjectName("label_17")
                self.cajaObservaciones = QtWidgets.QLineEdit(self.MenuAniadir)
                self.cajaObservaciones.setGeometry(QtCore.QRect(440, 250, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaObservaciones.setFont(font)
                self.cajaObservaciones.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaObservaciones.setObjectName("cajaObservaciones")
                self.BotonSituacion_3 = QtWidgets.QPushButton(self.MenuAniadir)
                self.BotonSituacion_3.setGeometry(QtCore.QRect(270, 420, 231, 31))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.BotonSituacion_3.setFont(font)
                self.BotonSituacion_3.setStyleSheet("QPushButton{\n"
        "    color:#fff;\n"
        "    border-radius:10px;\n"
        "    background:#EC3333\n"
        "    \n"
        "}\n"
        "QPushButthon{\n"
        "    color:black;\n"
        "    background:#D90808\n"
        "}")
                self.BotonSituacion_3.setObjectName("BotonSituacion_3")
                self.MenueEliminarUsuario.addTab(self.MenuAniadir, "")
                self.tab = QtWidgets.QWidget()
                self.tab.setObjectName("tab")
                self.cajaCalleSecundaria_3 = QtWidgets.QLineEdit(self.tab)
                self.cajaCalleSecundaria_3.setGeometry(QtCore.QRect(450, 190, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaCalleSecundaria_3.setFont(font)
                self.cajaCalleSecundaria_3.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaCalleSecundaria_3.setObjectName("cajaCalleSecundaria_3")
                self.cajaCallePrincipal_3 = QtWidgets.QLineEdit(self.tab)
                self.cajaCallePrincipal_3.setGeometry(QtCore.QRect(450, 140, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaCallePrincipal_3.setFont(font)
                self.cajaCallePrincipal_3.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaCallePrincipal_3.setObjectName("cajaCallePrincipal_3")
                self.cajaApellido_3 = QtWidgets.QLineEdit(self.tab)
                self.cajaApellido_3.setEnabled(False)
                self.cajaApellido_3.setGeometry(QtCore.QRect(90, 200, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaApellido_3.setFont(font)
                self.cajaApellido_3.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaApellido_3.setObjectName("cajaApellido_3")
                self.cajaTelefono_3 = QtWidgets.QLineEdit(self.tab)
                self.cajaTelefono_3.setEnabled(True)
                self.cajaTelefono_3.setGeometry(QtCore.QRect(90, 300, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaTelefono_3.setFont(font)
                self.cajaTelefono_3.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaTelefono_3.setObjectName("cajaTelefono_3")
                self.label_28 = QtWidgets.QLabel(self.tab)
                self.label_28.setGeometry(QtCore.QRect(450, 220, 81, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_28.setFont(font)
                self.label_28.setObjectName("label_28")
                self.label_8 = QtWidgets.QLabel(self.tab)
                self.label_8.setGeometry(QtCore.QRect(90, 280, 91, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_8.setFont(font)
                self.label_8.setObjectName("label_8")
                self.label_12 = QtWidgets.QLabel(self.tab)
                self.label_12.setGeometry(QtCore.QRect(90, 230, 91, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_12.setFont(font)
                self.label_12.setObjectName("label_12")
                self.cajaId_2 = QtWidgets.QLineEdit(self.tab)
                self.cajaId_2.setGeometry(QtCore.QRect(90, 150, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaId_2.setFont(font)
                self.cajaId_2.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaId_2.setObjectName("cajaId_2")
                self.cajaObservaciones_3 = QtWidgets.QLineEdit(self.tab)
                self.cajaObservaciones_3.setGeometry(QtCore.QRect(450, 290, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaObservaciones_3.setFont(font)
                self.cajaObservaciones_3.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaObservaciones_3.setObjectName("cajaObservaciones_3")
                self.label_30 = QtWidgets.QLabel(self.tab)
                self.label_30.setGeometry(QtCore.QRect(450, 270, 121, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_30.setFont(font)
                self.label_30.setObjectName("label_30")
                self.label_29 = QtWidgets.QLabel(self.tab)
                self.label_29.setGeometry(QtCore.QRect(450, 170, 121, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_29.setFont(font)
                self.label_29.setObjectName("label_29")
                self.cajaCaso_3 = QtWidgets.QLineEdit(self.tab)
                self.cajaCaso_3.setGeometry(QtCore.QRect(450, 240, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaCaso_3.setFont(font)
                self.cajaCaso_3.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaCaso_3.setObjectName("cajaCaso_3")
                self.cajaICiudad_3 = QtWidgets.QLineEdit(self.tab)
                self.cajaICiudad_3.setEnabled(True)
                self.cajaICiudad_3.setGeometry(QtCore.QRect(90, 350, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaICiudad_3.setFont(font)
                self.cajaICiudad_3.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaICiudad_3.setObjectName("cajaICiudad_3")
                self.label_9 = QtWidgets.QLabel(self.tab)
                self.label_9.setGeometry(QtCore.QRect(90, 130, 91, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_9.setFont(font)
                self.label_9.setObjectName("label_9")
                self.label_11 = QtWidgets.QLabel(self.tab)
                self.label_11.setGeometry(QtCore.QRect(90, 390, 171, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_11.setFont(font)
                self.label_11.setObjectName("label_11")
                self.label_31 = QtWidgets.QLabel(self.tab)
                self.label_31.setGeometry(QtCore.QRect(450, 120, 121, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_31.setFont(font)
                self.label_31.setObjectName("label_31")
                self.label_10 = QtWidgets.QLabel(self.tab)
                self.label_10.setGeometry(QtCore.QRect(90, 180, 91, 21))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_10.setFont(font)
                self.label_10.setObjectName("label_10")
                self.cajaNombre_3 = QtWidgets.QLineEdit(self.tab)
                self.cajaNombre_3.setEnabled(False)
                self.cajaNombre_3.setGeometry(QtCore.QRect(90, 250, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaNombre_3.setFont(font)
                self.cajaNombre_3.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaNombre_3.setObjectName("cajaNombre_3")
                self.cajaAvenida_3 = QtWidgets.QLineEdit(self.tab)
                self.cajaAvenida_3.setGeometry(QtCore.QRect(90, 410, 211, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.cajaAvenida_3.setFont(font)
                self.cajaAvenida_3.setStyleSheet("QLineEdit{\n"
        "background: transparent;color:#E84040;border:none;border-bottom:1px solid #756D6D;\n"
        "}\n"
        "")
                self.cajaAvenida_3.setObjectName("cajaAvenida_3")
                self.label_7 = QtWidgets.QLabel(self.tab)
                self.label_7.setGeometry(QtCore.QRect(90, 330, 161, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_7.setFont(font)
                self.label_7.setObjectName("label_7")
                self.label_32 = QtWidgets.QLabel(self.tab)
                self.label_32.setGeometry(QtCore.QRect(290, 20, 191, 31))
                font = QtGui.QFont()
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.label_32.setFont(font)
                self.label_32.setObjectName("label_32")
                self.BotonSituacion_4 = QtWidgets.QPushButton(self.tab)
                self.BotonSituacion_4.setGeometry(QtCore.QRect(440, 370, 231, 31))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.BotonSituacion_4.setFont(font)
                self.BotonSituacion_4.setStyleSheet("QPushButton{\n"
        "    color:#fff;\n"
        "    border-radius:10px;\n"
        "    background:#EC3333\n"
        "    \n"
        "}\n"
        "QPushButthon{\n"
        "    color:black;\n"
        "    background:#D90808\n"
        "}")
                self.BotonSituacion_4.setObjectName("BotonSituacion_4")
                self.BotonSituacion_5 = QtWidgets.QPushButton(self.tab)
                self.BotonSituacion_5.setGeometry(QtCore.QRect(440, 410, 231, 31))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.BotonSituacion_5.setFont(font)
                self.BotonSituacion_5.setStyleSheet("QPushButton{\n"
        "    color:#fff;\n"
        "    border-radius:10px;\n"
        "    background:#EC3333\n"
        "    \n"
        "}\n"
        "QPushButthon{\n"
        "    color:black;\n"
        "    background:#D90808\n"
        "}")
                self.BotonSituacion_5.setObjectName("BotonSituacion_5")
                self.BotonSituacion_6 = QtWidgets.QPushButton(self.tab)
                self.BotonSituacion_6.setGeometry(QtCore.QRect(440, 330, 231, 31))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.BotonSituacion_6.setFont(font)
                self.BotonSituacion_6.setStyleSheet("QPushButton{\n"
        "    color:#fff;\n"
        "    border-radius:10px;\n"
        "    background:#EC3333\n"
        "    \n"
        "}\n"
        "QPushButthon{\n"
        "    color:black;\n"
        "    background:#D90808\n"
        "}")
                self.BotonSituacion_6.setObjectName("BotonSituacion_6")
                self.MenueEliminarUsuario.addTab(self.tab, "")
                MenuCallCenter.setCentralWidget(self.centralwidget)
                self.statusbar = QtWidgets.QStatusBar(MenuCallCenter)
                self.statusbar.setObjectName("statusbar")
                MenuCallCenter.setStatusBar(self.statusbar)

                self.retranslateUi(MenuCallCenter)
                self.MenueEliminarUsuario.setCurrentIndex(0)
                self.BotonSituacion_3.clicked.connect(self.cajaId.clear) #
                self.BotonSituacion_3.clicked.connect(self.cajaApellido.clear) 
                self.BotonSituacion_3.clicked.connect(self.cajaNombre.clear)
                self.BotonSituacion_3.clicked.connect(self.cajaTelefono.clear)
                self.BotonSituacion_3.clicked.connect(self.cajaICiudad.clear)
                self.BotonSituacion_3.clicked.connect(self.cajaAvenida.clear)
                self.BotonSituacion_3.clicked.connect(self.cajaObservaciones.clear)
                self.BotonSituacion_3.clicked.connect(self.cajaCaso.clear) 
                self.BotonSituacion_3.clicked.connect(self.cajaCalleSecundaria.clear)
                self.BotonSituacion_3.clicked.connect(self.cajaCallePrincipal.clear) 
                self.BotonBuscar_2.clicked.connect(self.cajaId_3.clear) 
                self.BotonBuscar_2.clicked.connect(self.cajaApellido_2.clear) 
                self.BotonBuscar_2.clicked.connect(self.cajaNombre_2.clear) 
                self.BotonBuscar_2.clicked.connect(self.cajaTelefono_2.clear) 
                self.BotonBuscar_2.clicked.connect(self.cajaICiudad_2.clear) 
                self.BotonBuscar_2.clicked.connect(self.cajaAvenida_2.clear)
                self.BotonBuscar_2.clicked.connect(self.cajaObservaciones_2.clear) 
                self.BotonBuscar_2.clicked.connect(self.cajaCaso_2.clear) 
                self.BotonBuscar_2.clicked.connect(self.cajaCalleSecundaria_2.clear)
                self.BotonBuscar_2.clicked.connect(self.cajaCallePrincipal_2.clear)
                self.BotonSituacion_2.clicked.connect(self.guardarInforme)
                self.BotonSituacion_4.clicked.connect(self.cajaId_2.copy)
                self.BotonSituacion_6.clicked.connect(self.cajaId_2.clear) 
                self.BotonSituacion_6.clicked.connect(self.cajaApellido_3.clear) 
                self.BotonSituacion_6.clicked.connect(self.cajaNombre_3.clear) 
                self.BotonSituacion_6.clicked.connect(self.cajaTelefono_3.clear) 
                self.BotonSituacion_6.clicked.connect(self.cajaICiudad_3.clear) 
                self.BotonSituacion_6.clicked.connect(self.cajaAvenida_3.clear) 
                self.BotonSituacion_6.clicked.connect(self.cajaCallePrincipal_3.clear) 
                self.BotonSituacion_6.clicked.connect(self.cajaCalleSecundaria_3.clear) 
                self.BotonSituacion_6.clicked.connect(self.cajaCaso_3.clear) 
                self.BotonSituacion_6.clicked.connect(self.cajaObservaciones_3.clear) 
                self.BotonSituacion_5.clicked.connect(self.cajaAvenida_3.copy) 
                #===========================Acciones de los botones====================================================
                self.BotonSituacion.clicked.connect(self.funcionBuscar) 
                self.BotonBuscar.clicked.connect(self.funcionBuscar2)
        def funcionBuscar(self):
                id=int(self.cajaId.text())
                self.cajaApellido.setText(buscarId(id)[0]['nombre'])
                self.cajaNombre.setText(buscarId(id)[0]['apellido'])
                self.cajaTelefono.setText(buscarId(id)[0]['telefono'])
                self.cajaICiudad.setText(buscarId(id)[0]['direccion'])
        def guardarInforme(self):
                id=int(self.cajaId.text())
                apellido=str(self.cajaApellido.text())
                nombre=str(self.cajaNombre.text())
                telefono=str(self.cajaTelefono.text())
                ciudad=str(self.cajaICiudad.text())
                avenida=str(self.cajaAvenida.text())
                callePrincipal=str(self.cajaCallePrincipal.text())
                calleSecundaria=str(self.cajaCalleSecundaria.text())
                caso=str(self.cajaCaso.text())
                observaciones=str(self.cajaObservaciones.text())                
                documento={"_id":id, "nombre":nombre,"apellido":apellido,"telefono":telefono,"direccion":ciudad,"avenida":avenida,"callePrincipal":callePrincipal,"calleSecundaria":calleSecundaria,"caso":caso,"observaciones":observaciones}
                guardarInforme(documento)
        def funcionBuscar2(self):
                id=int(self.cajaId_3.text())
                self.cajaApellido_2.setText(buscarId2(id)[0]['nombre'])
                self.cajaNombre_2.setText(buscarId2(id)[0]['apellido'])
                self.cajaTelefono_2.setText(buscarId2(id)[0]['telefono'])
                self.cajaICiudad_2.setText(buscarId2(id)[0]['direccion'])
                self.cajaAvenida_2.setText(buscarId2(id)[0]['avenida'])
                self.cajaCallePrincipal_2.setText(buscarId2(id)[0]['callePrincipal'])
                self.cajaCalleSecundaria_2.setText(buscarId2(id)[0]['calleSecundaria'])
                self.cajaCaso_2.setText(buscarId2(id)[0]['caso'])
                self.cajaObservaciones_2.setText(buscarId2(id)[0]['observaciones'])


        def retranslateUi(self, MenuCallCenter):
                _translate = QtCore.QCoreApplication.translate
                MenuCallCenter.setWindowTitle(_translate("MenuCallCenter", "MainWindow"))
                self.BotonBuscar.setText(_translate("MenuCallCenter", "Buscar"))
                self.NombreAdmin.setText(_translate("MenuCallCenter", "Nombre Administrador"))
                self.IdAdministrador.setText(_translate("MenuCallCenter", "ID Administrador:"))
                self.label_18.setText(_translate("MenuCallCenter", "Caso"))
                self.label_19.setText(_translate("MenuCallCenter", "Ciudad"))
                self.label_20.setText(_translate("MenuCallCenter", "Telefono"))
                self.label_21.setText(_translate("MenuCallCenter", "Calle Secundaria"))
                self.label_22.setText(_translate("MenuCallCenter", "Observaciones"))
                self.label_23.setText(_translate("MenuCallCenter", "ID/ Cédula"))
                self.label_24.setText(_translate("MenuCallCenter", "Apellido"))
                self.label_25.setText(_translate("MenuCallCenter", "Calle principal"))
                self.label_26.setText(_translate("MenuCallCenter", "Avenida"))
                self.label_27.setText(_translate("MenuCallCenter", "Nombre"))
                self.BotonBuscar_2.setText(_translate("MenuCallCenter", "Limpiar Reporte"))
                self.MenueEliminarUsuario.setTabText(self.MenueEliminarUsuario.indexOf(self.MenuBuscar), _translate("MenuCallCenter", "Buscar Reporte"))
                self.BotonSituacion.setText(_translate("MenuCallCenter", "Buscar"))
                self.label.setText(_translate("MenuCallCenter", "ID/ Cédula"))
                self.label_2.setText(_translate("MenuCallCenter", "Apellido"))
                self.label_3.setText(_translate("MenuCallCenter", "Nombre"))
                self.label_4.setText(_translate("MenuCallCenter", "Telefono"))
                self.label_5.setText(_translate("MenuCallCenter", "Ciudad"))
                self.label_6.setText(_translate("MenuCallCenter", "Avenida"))
                self.BotonSituacion_2.setText(_translate("MenuCallCenter", "Agregar"))
                self.label_13.setText(_translate("MenuCallCenter", "Agregar informe"))
                self.label_14.setText(_translate("MenuCallCenter", "Calle principal"))
                self.label_15.setText(_translate("MenuCallCenter", "Calle Secundaria"))
                self.label_16.setText(_translate("MenuCallCenter", "Caso"))
                self.label_17.setText(_translate("MenuCallCenter", "Observaciones"))
                self.BotonSituacion_3.setText(_translate("MenuCallCenter", "Limpiar Campos"))
                self.MenueEliminarUsuario.setTabText(self.MenueEliminarUsuario.indexOf(self.MenuAniadir), _translate("MenuCallCenter", "Añadir Reporte"))
                self.label_28.setText(_translate("MenuCallCenter", "Caso"))
                self.label_8.setText(_translate("MenuCallCenter", "Telefono"))
                self.label_12.setText(_translate("MenuCallCenter", "Nombre"))
                self.label_30.setText(_translate("MenuCallCenter", "Observaciones"))
                self.label_29.setText(_translate("MenuCallCenter", "Calle Secundaria"))
                self.label_9.setText(_translate("MenuCallCenter", "ID/ Cédula"))
                self.label_11.setText(_translate("MenuCallCenter", "Avenida"))
                self.label_31.setText(_translate("MenuCallCenter", "Calle principal"))
                self.label_10.setText(_translate("MenuCallCenter", "Apellido"))
                self.label_7.setText(_translate("MenuCallCenter", "Ciudad"))
                self.label_32.setText(_translate("MenuCallCenter", "Eliminar Reporte"))
                self.BotonSituacion_4.setText(_translate("MenuCallCenter", "Buscar"))
                self.BotonSituacion_5.setText(_translate("MenuCallCenter", "Eliminar"))
                self.BotonSituacion_6.setText(_translate("MenuCallCenter", "Limpiar Campos"))
                self.MenueEliminarUsuario.setTabText(self.MenueEliminarUsuario.indexOf(self.tab), _translate("MenuCallCenter", "Eliminar Reporte"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MenuCallCenter = QtWidgets.QMainWindow()
    ui = Ui_MenuCallCenter()
    ui.setupUi(MenuCallCenter)
    MenuCallCenter.show()
    sys.exit(app.exec_())
